name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main

  fuzz:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: linux
          - os: macos
        include:
          - target:
              os: linux
            builder: ubuntu-latest
          - target:
              os: macos
            builder: macos-latest

    name: '${{ matrix.target.os }} Fuzz'
    runs-on: ${{ matrix.builder }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install engines (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update

          # libFuzzer
          sudo apt-get install -y clang

          # honggfuzz
          bash scripts/install_honggfuzz.sh
          echo "/opt/honggfuzz/usr/local/bin" >> "$GITHUB_PATH"

          # afl
          sudo apt-get install -y afl++
          sudo afl-system-config

      - name: Install engines (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update

          # libFuzzer
          brew install llvm
          echo "/opt/homebrew/opt/llvm/bin" >> "$GITHUB_PATH"

          # honggfuzz
          bash scripts/install_honggfuzz.sh
          echo "/opt/honggfuzz/usr/local/bin" >> "$GITHUB_PATH"

          # afl
          brew install afl++
          sudo afl-system-config

      - name: Install Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: 'stable'

      - name: Run fuzzing tests
        run: |
          nimble fuzz | tee out.txt
          for fuzzer in "libFuzzer" "honggfuzz" "afl"; do
            if [[ "$(uname -s)" == Darwin ]] && [[ $fuzzer == "honggfuzz" ]]; then
              continue
            fi
            (( $(grep -o "'$fuzzer' detected crash during" out.txt | wc -l) == 1 ))
          done
          ! grep -q "did not produce any test vectors" out.txt
