name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main

  fuzz:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: linux
          - os: macos
        include:
          - target:
              os: linux
            builder: ubuntu-latest
          - target:
              os: macos
            builder: macos-latest

    name: '${{ matrix.target.os }} Fuzz'
    runs-on: ${{ matrix.builder }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install engines (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang afl++
          bash scripts/install_honggfuzz.sh
          echo "/opt/honggfuzz/usr/local/bin" >> "$GITHUB_PATH"

      - name: Install engines (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install llvm afl++
          bash scripts/install_honggfuzz.sh
          echo "/opt/honggfuzz/usr/local/bin" >> "$GITHUB_PATH"
